// Copyright (c) 2015 Sergio Gonzalez. All rights reserved.
// License: https://github.com/serge-rgb/milton#license

#include "canvas.cc"
#include "color.cc"
#include "gl_helpers.cc"
#include "gui.cc"
#include "hardware_renderer.cc"
#include "hash.cc"
#include "localization.cc"
#include "memory.cc"
#include "milton.cc"
#include "persist.cc"
#include "platform_windows.cc"
#include "profiler.cc"
#include "sdl_milton.cc"
#include "shadergen.cc"
#include "StrokeList.cc"
#include "tests.cc"
#include "third_party_libs.cc"
#include "utils.cc"
#include "vector.cc"
